<?php

use Illuminate\Database\Seeder;

class Club extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('club')->delete();        
        DB::table('club')->insert([
            ['Nombre_Club' => 'A PLENO TENIS'],
            ['Nombre_Club' => '100 % MOTOCROSS'],
            ['Nombre_Club' => 'PIRATAS JUNIOR BASKETBALL CLUB'],
            ['Nombre_Club' => 'ATLETICO CHACARITA JUNIORS FILIAL COLOMBIA'],
            ['Nombre_Club' => 'ANDINO FUTBOL CLUB'],
            ['Nombre_Club' => 'A.C. SUR'],
            ['Nombre_Club' => 'A1'],
            ['Nombre_Club' => 'ABALB'],
            ['Nombre_Club' => 'ACADEMIA ALEMANA'],
            ['Nombre_Club' => 'ACADEMIA BOGOTANA DE FUTBOL'],
            ['Nombre_Club' => 'ACADEMIA BOGOTANA DE TALENTOS'],
            ['Nombre_Club' => 'ACADEMIA COLOMBIA'],
            ['Nombre_Club' => 'ACADEMIA COLOMBIANA DE FUTBOL ACOFUTBOL'],
            ['Nombre_Club' => 'ACADEMIA CRISTIANA FUTBOL FEMENINO'],
            ['Nombre_Club' => 'ACADEMIA DE BEISBOL AGUILAS CAPITALINAS'],
            ['Nombre_Club' => 'ACADEMIA DE FUTBOL ANTONIO NARIÑO L.15'],
            ['Nombre_Club' => 'ACADEMIA DE FUTBOL LEEDS UNITED â (antes SPORT TEAM CLUB)'],
            ['Nombre_Club' => 'ACADEMIA DE TALENTOS FUTBOL CLUB'],
            ['Nombre_Club' => 'ACADEMIA DELFOS'],
            ['Nombre_Club' => 'ACADEMIA EL DIAMANTE'],
            ['Nombre_Club' => 'ACADEMIA ESTUDIANTES'],
            ['Nombre_Club' => 'ACADEMIA FRANCESA DE FUTBOL'],
            ['Nombre_Club' => 'ACADEMIA FUTBOL CLUB BOGOTA'],
            ['Nombre_Club' => 'ACADEMIA IGUARAN FC'],
            ['Nombre_Club' => 'ACADEMIA NACIONAL DE FUTBOL'],
            ['Nombre_Club' => 'ACCA DE TIRO Y CAZA'],
            ['Nombre_Club' => 'ACCIONES'],
            ['Nombre_Club' => 'ACIP LA ROMA'],
            ['Nombre_Club' => 'ACUEDUCTO FUTBOL'],
            ['Nombre_Club' => 'DE KARATE DO ACUEDUCTO'],
            ['Nombre_Club' => 'ACUEDUCTO TEJO'],
            ['Nombre_Club' => 'ADB'],
            ['Nombre_Club' => 'ADI LA COCHITA'],
            ['Nombre_Club' => 'ADVANTIX'],
            ['Nombre_Club' => 'AEROCLUB BOGOTA'],
            ['Nombre_Club' => 'AEROCLUB PARACAIDISMO COLOMBIA'],
            ['Nombre_Club' => 'AEROSOUL'],
            ['Nombre_Club' => 'AEROSTACION'],
            ['Nombre_Club' => 'AGAPUS'],
            ['Nombre_Club' => 'AGROSERVICIOS EL CAMINO'],
            ['Nombre_Club' => 'AGUILAS'],
            ['Nombre_Club' => 'AGUILAS COLOMBIA'],
            ['Nombre_Club' => 'AGUILAS DEL SOL'],
            ['Nombre_Club' => 'AGUILAS SPORTING'],
            ['Nombre_Club' => 'AHIMSA'],
            ['Nombre_Club' => 'AJAX FCM FUTBOL CLUB'],
            ['Nombre_Club' => 'AJEDREZ UNIVERSITARIO'],
            ['Nombre_Club' => 'AKUATOR'],
            ['Nombre_Club' => 'ALADINO RACQUET CLUB'],
            ['Nombre_Club' => 'ALAND'],
            ['Nombre_Club' => 'ALBA REAL'],
            ['Nombre_Club' => 'ALBATROS'],
            ['Nombre_Club' => 'ALBATROS CYCLING TEAM'],
            ['Nombre_Club' => 'ALCATRAZ'],
            ['Nombre_Club' => 'ALCAZARES'],
            ['Nombre_Club' => 'ALEGRIA'],
            ['Nombre_Club' => 'ALEGRIA â ROLLING STARS'],
            ['Nombre_Club' => 'ALEJANDRINOS'],
            ['Nombre_Club' => 'ALEXANDRA VIVAS'],
            ['Nombre_Club' => 'ALEXMAN'],
            ['Nombre_Club' => 'ALFONSO CAÑON'],
            ['Nombre_Club' => 'ALFONSO LOPEZ LA VELEÑITA'],
            ['Nombre_Club' => 'ALFONSO SEPULVEDA'],
            ['Nombre_Club' => 'ALIANZA BOGOTA'],
            ['Nombre_Club' => 'ALIANZA ECUESTRE (Gamboa)'],
            ['Nombre_Club' => 'ALIANZA F.C.'],
            ['Nombre_Club' => 'ALIANZA JR'],
            ['Nombre_Club' => 'ALIANZA M-3 FUTSAL'],
            ['Nombre_Club' => 'ALIANZA RUCBY FOOTBALL CLUB'],
            ['Nombre_Club' => 'ALIANZA SPORT'],
            ['Nombre_Club' => 'ALIANZA SUBA F.C.'],
            ['Nombre_Club' => 'ALL POWERS SPORTAEROBICS'],
            ['Nombre_Club' => 'ALLEGRO NICOLAS FEDERMAN'],
            ['Nombre_Club' => 'ALLEMANG'],
            ['Nombre_Club' => 'ALMIRANTE COLON'],
            ['Nombre_Club' => 'ALPINE'],
            ['Nombre_Club' => 'ALTAVISTA CAMPEONES CON CORAZÃN'],
            ['Nombre_Club' => 'ALTIUS EAT'],
            ['Nombre_Club' => 'AMAZONAS'],
            ['Nombre_Club' => 'AMBALA F.C.'],
            ['Nombre_Club' => 'AMERICA EXTREMO'],
            ['Nombre_Club' => 'AMERICA TENIS CLUB Social'],
            ['Nombre_Club' => 'AMERICANINOS F.C.'],
            ['Nombre_Club' => 'AMERIOL SKATE CLUB'],
            ['Nombre_Club' => 'AMIGOS DEL AGUA'],
            ['Nombre_Club' => 'AMIGOS DEL VOLEIBOL'],
            ['Nombre_Club' => 'AMISTAD'],
            ['Nombre_Club' => 'ANDECRAC'],
            ['Nombre_Club' => 'ANDES F.C.'],
            ['Nombre_Club' => 'ANDINOS'],
            ['Nombre_Club' => 'ANDRES ESCOBAR'],
            ['Nombre_Club' => 'ANDRZEJ GRUBBA'],
            ['Nombre_Club' => 'ANGEL F.M. BOXING CLUB'],
            ['Nombre_Club' => 'LOS ANGELES'],
            ['Nombre_Club' => 'ANGELES FUTBOL'],
            ['Nombre_Club' => 'ANGELS SKATE CLUB'],
            ['Nombre_Club' => 'ANONIMOS RUGBY'],
            ['Nombre_Club' => 'ANTARES DE LA SABANA'],
            ['Nombre_Club' => 'ANTILOPES BASKETBALL CLUB '],
            ['Nombre_Club' => 'AÑOS MARAVILLOSOS'],
            ['Nombre_Club' => 'APA - LTB']//104
            ]);
    }
}
